steps:
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'hands-on-aks-sp-devops01-handson-1687534607107'
trigger:
- main
pool:
  vmImage: ubuntu-latest
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: NodeTool@0  # Adicione a nova tarefa dentro do bloco de sequência
  inputs:
    versionSpec: '10.x'
  displayName: 'Another task'  # Defina um nome adequado para a nova tarefa
